"""Added name column

Revision ID: 850e57b53d0e
Revises: 4d3d7cea2efd
Create Date: 2021-09-22 13:49:01.783144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '850e57b53d0e'
down_revision = '4d3d7cea2efd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
