"""Added name column

Revision ID: cf038bb2ec50
Revises: 872ae9822b21
Create Date: 2021-09-22 13:51:26.427157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf038bb2ec50'
down_revision = '872ae9822b21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
